# Generated by Django 5.2.4 on 2025-07-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_stock'),
        ('ventas', '0003_pedido_nombre_cliente_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='descripcion_personalizada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='productos.producto'),
        ),
    ]
