# Generated by Django 5.2.4 on 2025-07-25 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_detallepedido_descripcion_personalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
