# Generated by Django 5.2.4 on 2025-07-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_pedido_fecha_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'Abierto'), ('FACTURADO', 'Facturado'), ('ANULADO', 'Anulado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10),
        ),
    ]
