# Generated by Django 5.2.4 on 2025-07-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0001_initial'),
        ('ventas', '0003_pedido_nombre_cliente_alter_pedido_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rondabolirana',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rondas_bolirana', to='ventas.pedido'),
        ),
    ]
